using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.AspNetCore.Mvc.Rendering;

namespace OrangeJuice.Models
{
	public class Orange
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Farm { get; set; }

		// Specifies Display Name
		[Display(Name = "Harvest Date")]
		// Specifies DateTime to just include date
		[DataType(DataType.Date)]
		public DateTime HarvestDate { get; set; }

		// specifies wieght as decimal(precision, scale)
		// precision is the max number of digits needed to express a single weight value
		// scale is the max number of decimals needed
		[Column(TypeName = "decimal(18, 2)")]
		public decimal Weight { get; set; }
		public string Juiciness { get; set; }
	}

	public class FarmViewModel
	{
		public List<Orange> Oranges { get; set; }
		public SelectList Farms { get; set; }
		/* 
		 * Why is the OrangeFarm property required in the FarmViewModel, but not SearchString?
		 * 
		 * Both referenced here:
			<p>
				<select asp-for="OrangeFarm" asp-items="Model.Farms">
					<option value="">All</option>
				</select>

				Title: <input type="text" name="SearchString">
				<input type="submit" value="Search" />
			</p>
		 * 
		 * Generated HTML:
			<form method="get" action="/Oranges">
				<p>
					<select id="OrangeFarm" name="OrangeFarm">
					<option value="">All</option>
					<option>Dunder-Mifflin Orange Farms</option>
					<option>Happy Orange Farms</option>
					</select>
					
					Title: <input type="text" name="SearchString">
					<input type="submit" value="Search" />
				</p>
			</form>
		 * 
		 * When debugging, I can't find any times where OrangeFarm has a value.
		 * So why is the reference necessary?
		 * 
		 * The id="OrangeFarm" tag must be the culprit. It is generated by asp-for="OrangeFarm".
		 * 
		 * Switched:
		 * <select asp-for="OrangeFarm" asp-items="Model.Farms">
		 * To:
		 * <select name="OrangeFarm" asp-items="Model.Farms">
		 * 
		 * And it works without the OrangeFarm property in the FarmViewModel!
		 */
		//public string OrangeFarm { get; set; }
		//public string SearchString { get; set; }
	}
}